catalog:
  '@types/better-sqlite3': ^7.6.12
  '@types/node': ^24.9.2
  '@vitest/coverage-v8': ^2.1.8
  better-sqlite3: ^11.5.0
  tsup: ^8.3.5
  tsx: ^4.19.2
  typescript: ^5.9.2
  vitest: ^2.1.8
  zod: ^3.25.50

  
packages:
  - 'apps/*'
  - 'packages/*'
  - 'turbo/generators'

configDependencies:
  '@pnpm/trusted-deps': 0.1.1+sha512-jI3PWNv2zCg9+KHI3qQTsa534c5nisZQrHFeWSyyHoUXcuzvjkXxQKPFLJ/qtNAF+PtKHDlRntO2aZKb3VDuHQ==

onlyBuiltDependenciesFile: node_modules/.pnpm-config/@pnpm/trusted-deps/allow.json

onlyBuiltDependencies:
  - core-js-pure
  - unrs-resolver
  - 'better-sqlite3'
