packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@types/better-sqlite3': ^7.6.12
  '@types/node': ^24.9.2
  '@vitest/coverage-v8': ^2.1.8
  better-sqlite3: ^11.5.0
  tsup: ^8.3.5
  tsx: ^4.19.2
  typescript: ^5.9.2
  vitest: ^2.1.8
  zod: ^3.25.50

onlyBuiltDependencies:
  - 'better-sqlite3'